server:
  port: 8000

spring:
  main:
    web-application-type: reactive

  application:
    name: gateway-01
  cloud:
    gateway:
      routes:

        # 테스트
        - id: service-01 # route id
          uri: lb://service-01 # load balancing
          predicates:
            - Path=/service-01/** # routing rule

        # 로그인
        - id: service-01
          uri: lb://service-01
          predicates:
            - Path=/login
            - Method=POST
          filters:
            - RewritePath=/login, /user/login
            - RemoveRequestHeader=Cookie


        - id: service-02
          uri: lb://service-02
          predicates:
            - Path=/service-02/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

token:
  refresh-token-header: RefreshToken
  roles: roles
  secret: aG5nc2lodDM4N3locndzYW9ocmY4OWFyeWhnM3c5Z3Izd3E2eXI4dzN5aHJvOXczcg==
  access-token-expiration: 10800000 # 3 hours
  refresh-token-expiration: 300000 # 3 days
