server:
  port: 8000

spring:
  main:
    web-application-type: reactive

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  application:
    name: gateway-01
  cloud:
    gateway:
      routes:

        # 1번 서비스 테스트
        - id: service-01 # route id
          uri: lb://service-01 # load balancing
          predicates:
            - Path=/service-01/** # routing rule

        # 2번 서비스 테스트
        - id: service-02
          uri: lb://service-02
          predicates:
            - Path=/service-02/**

        # 1번과 2번 상호작용 테스트
        - id: service-01
          uri: lb://service-01
          predicates:
            - Path=/interaction
            - Method=GET
          filters:
            - RewritePath=/interaction, /user/interaction

      # 2번쪽 더미 데이터
        - id: service-02
          uri: lb://service-02
          predicates:
              - Path=/dummy
              - Method=GET
          filters:
              - RewritePath=/dummy, /board/dummy


        # 로그인
        - id: service-01
          uri: lb://service-01
          predicates:
            - Path=/login
            - Method=POST
          filters:
            - RewritePath=/login, /user/login
            - RemoveRequestHeader=Cookie

          # 회원 가입
        - id: service-01
          uri: lb://service-01
          predicates:
            - Path=/signup
            - Method=POST
          filters:
            - RewritePath=/signup, /user/signup
            - RemoveRequestHeader=Cookie

          # 회원 정보 조회
        - id: service-01
          uri: lb://service-01
          predicates:
            - Path=/user
            - Method=GET
          filters:
            - RewritePath=/user, /user/info
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

# /actuator/refresh 엔드포인트 활성화
management:
  endpoints:
    web:
      exposure:
        include: refresh
